# Generated by Django 4.2.3 on 2023-10-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='唯一識別碼')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('contact', models.CharField(blank=True, max_length=15, null=True, verbose_name='聯絡電話')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='電子郵件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客列表',
            },
        ),
    ]
