# Generated by Django 4.2.3 on 2023-11-16 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_dayofweek_day_alter_dayofweek_vendor'),
        ('MenuItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='extra_option',
            field=models.ManyToManyField(to='MenuItem.extraoption', verbose_name='額外選項'),
        ),
        migrations.CreateModel(
            name='RequiredOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='必選選項', max_length=100, verbose_name='名稱')),
                ('description', models.TextField(default='', null=True, verbose_name='解釋')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='價格')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.vendor', verbose_name='廠商')),
            ],
            options={
                'verbose_name': '必選選項',
                'verbose_name_plural': '必選選項',
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='required_option',
            field=models.ManyToManyField(to='MenuItem.requiredoption', verbose_name='必選選項'),
        ),
    ]
