# Generated by Django 4.2.3 on 2023-11-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_dayofweek_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofweek',
            name='day',
            field=models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五')], unique=True, verbose_name='星期'),
        ),
        migrations.AlterField(
            model_name='dayofweek',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_of_week', to='Shop.vendor', verbose_name='廠商'),
        ),
    ]
