# Generated by Django 4.2.3 on 2023-11-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_alter_dayofweek_day_alter_dayofweek_rest_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofweek',
            name='day',
            field=models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五')], default=1, verbose_name='星期'),
        ),
    ]
