# Generated by Django 4.2.3 on 2023-12-30 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_alter_dayofweek_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotions', models.TextField(blank=True, null=True, verbose_name='促銷信息')),
                ('is_show_promotion_price', models.BooleanField(default=False, verbose_name='顯示促銷價格')),
                ('promotion_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promotion_type', models.CharField(max_length=50, null=True, verbose_name='促銷類型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='Shop.vendor', verbose_name='供應商')),
            ],
            options={
                'verbose_name': '促銷',
                'verbose_name_plural': '促銷',
            },
        ),
    ]
