# Generated by Django 4.2.3 on 2023-12-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': '廠商促銷', 'verbose_name_plural': '促銷'},
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_image',
            field=models.ImageField(blank=True, null=True, upload_to='promotion_images/', verbose_name='促銷照片'),
        ),
    ]
