# Generated by Django 4.2.3 on 2023-12-30 01:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_alter_promotion_promotion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='促銷結束時間'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='促銷開始時間'),
            preserve_default=False,
        ),
    ]
