# Generated by Django 4.2.3 on 2023-12-30 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_alter_promotion_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('max_purchase_count', models.PositiveIntegerField(verbose_name='最大購買人數')),
                ('simultaneous_purchase_limit', models.PositiveIntegerField(verbose_name='同時間購買人數限制')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.vendor', verbose_name='廠商')),
            ],
            options={
                'unique_together': {('vendor', 'date')},
            },
        ),
    ]
