# Generated by Django 4.2.3 on 2023-12-30 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_vendordailymetrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendordailymetrics',
            options={'verbose_name': '廠商每日指標', 'verbose_name_plural': '每日指標'},
        ),
        migrations.AddField(
            model_name='currentstate',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='日期'),
        ),
        migrations.AlterUniqueTogether(
            name='currentstate',
            unique_together={('vendor', 'date')},
        ),
    ]
