# Generated by Django 4.2.3 on 2023-12-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_alter_vendordailymetrics_options_currentstate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='max_purchase_count',
            field=models.PositiveIntegerField(default=30, verbose_name='最大購買人數'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='simultaneous_purchase_limit',
            field=models.PositiveIntegerField(default=5, verbose_name='同時間購買人數限制'),
        ),
    ]
