# Generated by Django 4.2.3 on 2024-01-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_currentstate_shopping_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_testing', models.BooleanField(default=False, verbose_name='是否正在測試')),
                ('is_trial_run', models.BooleanField(default=False, verbose_name='是否試營運')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否活動')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '廠商設定',
                'verbose_name_plural': '廠商設定',
            },
        ),
    ]
