# Generated by Django 4.2.3 on 2024-01-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0020_vendorsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordailymetrics',
            name='current_purchase_count',
            field=models.PositiveIntegerField(default=0, verbose_name='現在購買人數'),
        ),
    ]
