# Generated by Django 4.2.3 on 2024-01-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0022_alter_vendor_preorder_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='preorder_qty',
            field=models.IntegerField(default=20, verbose_name='預訂數量'),
        ),
    ]
