version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpop-server-web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  # celery:
  #   build: .
  #   container_name: cpop-server-celery
  #   command: celery -A Backend worker -l info

  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"
  # db:
  #   image: "postgres:latest"
  #   environment:
  #     POSTGRES_DB: your_db_name
  #     POSTGRES_USER: your_db_user
  #     POSTGRES_PASSWORD: your_db_password
