# Generated by Django 4.2.3 on 2023-11-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItem', '0004_alter_menuitem_vendor_alter_menustatus_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='標題'),
        ),
    ]
