# Generated by Django 4.2.3 on 2023-12-30 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItem', '0005_alter_menuitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menustatus',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='menustatus',
            unique_together={('menu_item', 'date')},
        ),
    ]
