# Generated by Django 4.2.3 on 2024-01-03 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItem', '0008_alter_menustatus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menustatus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
