# Generated by Django 4.2.3 on 2024-01-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItem', '0010_alter_menustatus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='menustatus',
            name='preorder_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='預訂數量'),
        ),
    ]
