# Generated by Django 4.2.3 on 2024-01-22 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItem', '0011_menustatus_preorder_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='remaining_quantity',
        ),
    ]
