# Generated by Django 4.2.3 on 2023-11-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='廠商名稱')),
                ('principal', models.CharField(max_length=255, verbose_name='負責人')),
                ('email', models.CharField(max_length=255, verbose_name='電子郵件')),
                ('contact', models.CharField(max_length=15, verbose_name='聯絡電話')),
                ('campus_name', models.CharField(choices=[('建功校區', '建功校區'), ('第一校區', '第一校區'), ('燕巢校區', '燕巢校區')], max_length=255, verbose_name='校區名稱')),
                ('vendor_img_url', models.ImageField(blank=True, null=True, upload_to='vendor_images/', verbose_name='廠商圖片URL')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='其他資訊')),
                ('promotions', models.TextField(blank=True, null=True, verbose_name='促銷信息')),
                ('shop_url', models.URLField(blank=True, null=True, verbose_name='商店連結URL')),
                ('ig_url', models.URLField(blank=True, null=True, verbose_name='Instagram連結URL')),
                ('fd_url', models.URLField(blank=True, null=True, verbose_name='Facebook連結URL')),
                ('preorder_qty', models.IntegerField(blank=True, null=True, verbose_name='預訂數量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '廠商',
                'verbose_name_plural': '廠商',
            },
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五')], unique=True, verbose_name='星期')),
                ('open_time', models.TimeField(default='08:00', verbose_name='營業時間')),
                ('close_time', models.TimeField(default='17:00', verbose_name='關閉時間')),
                ('rest_open_time', models.TimeField(blank=True, default='15:00', null=True, verbose_name='休息開始時間')),
                ('rest_close_time', models.TimeField(blank=True, default='17:00', null=True, verbose_name='休息結束時間')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_of_week', to='Shop.vendor', verbose_name='星期')),
            ],
            options={
                'verbose_name': '廠商時間',
                'verbose_name_plural': '廠商時間',
            },
        ),
        migrations.CreateModel(
            name='CurrentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.IntegerField(default=0, verbose_name='當前號碼')),
                ('wait_number', models.IntegerField(default=0, verbose_name='等待號碼')),
                ('is_start', models.BooleanField(default=False, verbose_name='是否開業')),
                ('is_delivery_available', models.BooleanField(default=False, verbose_name='是否提供外送')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_state', to='Shop.vendor', verbose_name='供應商')),
            ],
            options={
                'verbose_name': '商店狀態',
                'verbose_name_plural': '商店狀態',
            },
        ),
    ]
