# Generated by Django 4.2.3 on 2023-11-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofweek',
            name='day',
            field=models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五')], unique=True, verbose_name='廠商'),
        ),
    ]
