# Generated by Django 4.2.3 on 2023-11-16 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_remove_dayofweek_vendors_dayofweek_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofweek',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_of_week', to='Shop.vendor', verbose_name='廠商'),
        ),
    ]
