# Generated by Django 4.2.3 on 2023-11-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_alter_dayofweek_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofweek',
            name='day',
            field=models.IntegerField(blank=True, choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五')], null=True, verbose_name='星期'),
        ),
        migrations.AlterField(
            model_name='dayofweek',
            name='rest_close_time',
            field=models.TimeField(default='17:00', verbose_name='休息結束時間'),
        ),
        migrations.AlterField(
            model_name='dayofweek',
            name='rest_open_time',
            field=models.TimeField(default='15:00', verbose_name='休息開始時間'),
        ),
    ]
