# Generated by Django 4.2.3 on 2024-02-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customer_blacklist_groups_customer_whitelist_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='blacklist_groups',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='whitelist_groups',
        ),
    ]
