# Generated by Django 4.2.3 on 2024-02-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Customer', '0003_remove_customer_blacklist_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='唯一識別碼')),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memberships', to='auth.group')),
            ],
        ),
    ]
