# Generated by Django 4.2.3 on 2024-02-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Customer', '0004_customergroupmembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customergroupmembership',
            options={'verbose_name': '顧客群組', 'verbose_name_plural': '顧客群組'},
        ),
        migrations.AlterField(
            model_name='customergroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memberships', to='auth.group', verbose_name='群組'),
        ),
        migrations.AlterField(
            model_name='customergroupmembership',
            name='is_blacklisted',
            field=models.BooleanField(default=False, verbose_name='是否是黑名單'),
        ),
    ]
    
    
