# Generated by Django 4.2.3 on 2024-02-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_customergroupmembership_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customergroupmembership',
            name='is_blacklisted',
        ),
    ]
