# Generated by Django 4.2.3 on 2023-12-29 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Shop', '0010_alter_dayofweek_day'),
        ('MenuItem', '0005_alter_menuitem_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(verbose_name='訂單日期')),
                ('take_time', models.DateTimeField(verbose_name='取餐時間')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='總金額')),
                ('order_status', models.CharField(choices=[('pending', '已下單'), ('processing', '製作中'), ('completed', '完成'), ('canceled', '取消')], default='pending', max_length=50, verbose_name='訂單狀態')),
                ('confirmation_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='哈希加密')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='Customer.customer', verbose_name='顧客')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='Shop.vendor', verbose_name='供應商')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單列表',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('extra_option', models.ManyToManyField(to='MenuItem.extraoption', verbose_name='額外選項')),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='MenuItem.menuitem', verbose_name='產品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Order.order')),
                ('required_option', models.ManyToManyField(to='MenuItem.requiredoption', verbose_name='必選選項')),
            ],
            options={
                'verbose_name': '訂單產品',
                'verbose_name_plural': '訂單產品列表',
            },
        ),
    ]
