# Generated by Django 4.2.3 on 2023-12-27 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItem', '0005_alter_menuitem_title'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='哈希加密'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('extra_option', models.ManyToManyField(to='MenuItem.extraoption', verbose_name='額外選項')),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='MenuItem.menuitem', verbose_name='產品')),
                ('required_option', models.ManyToManyField(to='MenuItem.requiredoption', verbose_name='必選選項')),
            ],
            options={
                'verbose_name': '訂單產品',
                'verbose_name_plural': '訂單產品列表',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='order_items', to='Order.orderitem', verbose_name='訂單項目'),
        ),
    ]
