# Generated by Django 4.2.3 on 2023-12-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('created', '創建'), ('pending', '已下單'), ('processing', '製作中'), ('completed', '完成'), ('canceled', '取消'), ('error', '錯誤')], default='pending', max_length=50, verbose_name='訂單狀態'),
        ),
    ]
