# Generated by Django 4.2.3 on 2024-01-21 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('Order', '0004_alter_order_order_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='交易動作')),
                ('timestamp', models.DateTimeField(
                    auto_now_add=True, verbose_name='時間戳記')),
                ('details', models.TextField(
                    blank=True, null=True, verbose_name='交易詳情')),
                ('customer', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='Customer.customer', verbose_name='使用者')),
            ],
            options={
                'verbose_name': '交易日誌',
                'verbose_name_plural': '交易日誌',
            },
        ),
    ]
