# Generated by Django 4.2.3 on 2023-11-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_uri', models.URLField()),
                ('referrer', models.URLField()),
                ('blocked_uri', models.URLField()),
            ],
        ),
    ]
