# Generated by Django 4.2.3 on 2023-09-28 05:05

import Track.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashbroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, validators=[Track.validators.non_negative_validator])),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MostPopularStore',
            fields=[
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='most_popular', serialize=False, to='Shop.shop')),
                ('count', models.PositiveIntegerField(default=0, validators=[Track.validators.non_negative_validator])),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitsandPageViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0, validators=[Track.validators.non_negative_validator], verbose_name='visitsandPageViews_count')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitsandPageViews', to='Shop.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TotalUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0, validators=[Track.validators.non_negative_validator], verbose_name='total_users_count')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_users', to='Shop.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TotalSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0, validators=[Track.validators.non_negative_validator], verbose_name='total_sales_count')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_sales', to='Shop.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TotalOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0, validators=[Track.validators.non_negative_validator], verbose_name='total_orders_count')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_orders', to='Shop.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0, validators=[Track.validators.non_negative_validator], verbose_name='daily_sales_count')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='Shop.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0, validators=[Track.validators.non_negative_validator], verbose_name='daily_total_orders_count')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_total_orders', to='Shop.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyNewUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0, validators=[Track.validators.non_negative_validator], verbose_name='daily_new_users_count')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_new_users', to='Shop.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyActiveUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0, validators=[Track.validators.non_negative_validator], verbose_name='daily_active_users_count')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_active_users', to='Shop.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActiveUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0, validators=[Track.validators.non_negative_validator], verbose_name='active_users_count')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to='Shop.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
