# Generated by Django 4.2.3 on 2023-10-01 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_alter_vendor_uid'),
        ('Track', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeusers',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='dailyactiveusers',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='dailynewusers',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='dailyorders',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='dailysales',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='mostpopularstore',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='totalorders',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='totalsales',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='totalusers',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='visitsandpageviews',
            name='shop',
        ),
        migrations.AddField(
            model_name='activeusers',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to='Shop.vendor'),
        ),
        migrations.AddField(
            model_name='dailyactiveusers',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='daily_active_users', to='Shop.vendor'),
        ),
        migrations.AddField(
            model_name='dailynewusers',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='daily_new_users', to='Shop.vendor'),
        ),
        migrations.AddField(
            model_name='dailyorders',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='daily_total_orders', to='Shop.vendor'),
        ),
        migrations.AddField(
            model_name='dailysales',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='Shop.vendor'),
        ),
        migrations.AddField(
            model_name='mostpopularstore',
            name='vendor',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='most_popular', serialize=False, to='Shop.vendor'),
        ),
        migrations.AddField(
            model_name='totalorders',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='total_orders', to='Shop.vendor'),
        ),
        migrations.AddField(
            model_name='totalsales',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='total_sales', to='Shop.vendor'),
        ),
        migrations.AddField(
            model_name='totalusers',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='total_users', to='Shop.vendor'),
        ),
        migrations.AddField(
            model_name='visitsandpageviews',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='visitsandPageViews', to='Shop.vendor'),
        ),
    ]
