# Generated by Django 4.2.3 on 2023-10-01 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_alter_vendor_uid'),
        ('Track', '0002_remove_activeusers_shop_remove_dailyactiveusers_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeusers',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to='Shop.vendor'),
        ),
        migrations.AlterField(
            model_name='dailyactiveusers',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_active_users', to='Shop.vendor'),
        ),
        migrations.AlterField(
            model_name='dailynewusers',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_new_users', to='Shop.vendor'),
        ),
        migrations.AlterField(
            model_name='dailyorders',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_total_orders', to='Shop.vendor'),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='Shop.vendor'),
        ),
        migrations.AlterField(
            model_name='totalorders',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_orders', to='Shop.vendor'),
        ),
        migrations.AlterField(
            model_name='totalsales',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_sales', to='Shop.vendor'),
        ),
        migrations.AlterField(
            model_name='totalusers',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_users', to='Shop.vendor'),
        ),
        migrations.AlterField(
            model_name='visitsandpageviews',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitsandPageViews', to='Shop.vendor'),
        ),
    ]
