# Generated by Django 4.2.3 on 2023-10-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0003_alter_activeusers_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalusers',
            name='vendor',
        ),
    ]
