# Generated by Django 4.2.3 on 2023-10-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0004_remove_totalusers_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitsandpageviews',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='visitsandpageviews',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
